/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import type { ReactNode } from "react";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import "./globals.css";
import { theme } from "@/theme";
import MainApp from "@/components/app-shell/main-app";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript></ColorSchemeScript>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Fjalla+One&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body>
                <MantineProvider theme={theme}>
                    <MainApp>
                        {children}
                        <Footer></Footer>
                    </MainApp>
                </MantineProvider>
            </body>
        </html>
    );
}
