// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = Grid3X3Slice | AboutUsHeaderSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type ContactDocumentDataSlicesSlice = PageHeaderSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type FooterDocumentDataSlicesSlice = FooterColumnSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * ContactTitle field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacttitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contacttitle: prismic.RichTextField;

  /**
   * ContactContent field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contactcontent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contactcontent: prismic.RichTextField;

  /**
   * ContactImage field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contactimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  contactimage: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | FramesImageSlice
  | FaqSlice
  | StepsSlice
  | HeroSliderSlice
  | TetimonialsSlice
  | TextAndImageTabsSlice
  | PopularProductsSlice
  | BenefitsSlice
  | LandingPageSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type MainMenuDocumentDataSlicesSlice = NavigationMenuSlice;

/**
 * Content for Main Menu documents
 */
interface MainMenuDocumentData {
  /**
   * Logo field in *Main Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * NavLink field in *Main Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.navlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navlink: prismic.LinkField;

  /**
   * Slice Zone field in *Main Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MainMenuDocumentDataSlicesSlice>;
}

/**
 * Main Menu document from Prismic
 *
 * - **API ID**: `main_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainMenuDocumentData>,
    "main_menu",
    Lang
  >;

type MobileNavbarDocumentDataSlicesSlice = MobileNavbrSlice;

/**
 * Content for Mobile Navbar documents
 */
interface MobileNavbarDocumentData {
  /**
   * Slice Zone field in *Mobile Navbar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_navbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MobileNavbarDocumentDataSlicesSlice>;
}

/**
 * Mobile Navbar document from Prismic
 *
 * - **API ID**: `mobile_navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MobileNavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MobileNavbarDocumentData>,
    "mobile_navbar",
    Lang
  >;

type PageDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProductsDocumentDataSlicesSlice = FormInputSlice | PageHeaderSlice;

/**
 * Content for Products documents
 */
interface ProductsDocumentData {
  /**
   * Slice Zone field in *Products*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: products.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductsDocumentDataSlicesSlice> /**
   * Meta Title field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: products.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: products.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Products document from Prismic
 *
 * - **API ID**: `products`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProductsDocumentData>,
    "products",
    Lang
  >;

type ServicesDocumentDataSlicesSlice =
  | HeroSliderSlice
  | PageHeaderSlice
  | TextAndImageTabsSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | ContactDocument
  | FooterDocument
  | HomepageDocument
  | MainMenuDocument
  | MobileNavbarDocument
  | PageDocument
  | ProductsDocument
  | ServicesDocument;

/**
 * Item in *AboutUsHeader → Default → Primary → items*
 */
export interface AboutUsHeaderSliceDefaultPrimaryItemsItem {
  /**
   * Numbers field in *AboutUsHeader → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.items[].numbers
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  numbers: prismic.RichTextField;

  /**
   * Description field in *AboutUsHeader → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *AboutUsHeader → Default → Primary → stack*
 */
export interface AboutUsHeaderSliceDefaultPrimaryStackItem {
  /**
   * Quality field in *AboutUsHeader → Default → Primary → stack*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.stack[].quality
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quality: prismic.RichTextField;

  /**
   * Para field in *AboutUsHeader → Default → Primary → stack*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.stack[].para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;
}

/**
 * Primary content in *AboutUsHeader → Default → Primary*
 */
export interface AboutUsHeaderSliceDefaultPrimary {
  /**
   * Heading field in *AboutUsHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Paragraph field in *AboutUsHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Subtitle field in *AboutUsHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Title field in *AboutUsHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * items field in *AboutUsHeader → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<AboutUsHeaderSliceDefaultPrimaryItemsItem>
  >;

  /**
   * stack field in *AboutUsHeader → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.stack[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stack: prismic.GroupField<
    Simplify<AboutUsHeaderSliceDefaultPrimaryStackItem>
  >;

  /**
   * Image field in *AboutUsHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_header.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutUsHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsHeader*
 */
type AboutUsHeaderSliceVariation = AboutUsHeaderSliceDefault;

/**
 * AboutUsHeader Shared Slice
 *
 * - **API ID**: `about_us_header`
 * - **Description**: AboutUsHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsHeaderSlice = prismic.SharedSlice<
  "about_us_header",
  AboutUsHeaderSliceVariation
>;

/**
 * Item in *Benefits → Default → Primary → Card*
 */
export interface BenefitsSliceDefaultPrimaryCardItem {
  /**
   * CardTitle field in *Benefits → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.card[].cardtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardtitle: prismic.RichTextField;

  /**
   * CardPara field in *Benefits → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.card[].cardpara
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardpara: prismic.RichTextField;
}

/**
 * Primary content in *Benefits → Default → Primary*
 */
export interface BenefitsSliceDefaultPrimary {
  /**
   * Title field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Para field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;

  /**
   * Card field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<BenefitsSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for Benefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BenefitsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Benefits*
 */
type BenefitsSliceVariation = BenefitsSliceDefault;

/**
 * Benefits Shared Slice
 *
 * - **API ID**: `benefits`
 * - **Description**: Benefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSlice = prismic.SharedSlice<
  "benefits",
  BenefitsSliceVariation
>;

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Image field in *Faq → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Item in *FooterColumn → Default → Primary → items*
 */
export interface FooterColumnSliceDefaultPrimaryItemsItem {
  /**
   * NavLink field in *FooterColumn → Default → Primary → items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.default.primary.items[].navlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navlink: prismic.LinkField;

  /**
   * NavLinkText field in *FooterColumn → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.default.primary.items[].navlinktext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  navlinktext: prismic.RichTextField;
}

/**
 * Item in *FooterColumn → Address → Primary → items*
 */
export interface FooterColumnSliceAddressPrimaryItemsItem {
  /**
   * Address field in *FooterColumn → Address → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.address.primary.items[].address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;
}

/**
 * Item in *FooterColumn → Policy → Primary → items*
 */
export interface FooterColumnSlicePolicyPrimaryItemsItem {
  /**
   * NavLink field in *FooterColumn → Policy → Primary → items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.policy.primary.items[].navlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navlink: prismic.LinkField;

  /**
   * NavLinkText field in *FooterColumn → Policy → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.policy.primary.items[].navlinktext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  navlinktext: prismic.RichTextField;
}

/**
 * Primary content in *FooterColumn → Default → Primary*
 */
export interface FooterColumnSliceDefaultPrimary {
  /**
   * Title field in *FooterColumn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * items field in *FooterColumn → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<FooterColumnSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for FooterColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterColumnSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *FooterColumn → Address → Primary*
 */
export interface FooterColumnSliceAddressPrimary {
  /**
   * Title field in *FooterColumn → Address → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.address.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Download field in *FooterColumn → Address → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.address.primary.download
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  download: prismic.LinkField;

  /**
   * items field in *FooterColumn → Address → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.address.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<FooterColumnSliceAddressPrimaryItemsItem>>;

  /**
   * FooterLogo field in *FooterColumn → Address → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.address.primary.footerlogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footerlogo: prismic.ImageField<never>;
}

/**
 * Address variation for FooterColumn Slice
 *
 * - **API ID**: `address`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterColumnSliceAddress = prismic.SharedSliceVariation<
  "address",
  Simplify<FooterColumnSliceAddressPrimary>,
  never
>;

/**
 * Primary content in *FooterColumn → Contact → Primary*
 */
export interface FooterColumnSliceContactPrimary {
  /**
   * Title field in *FooterColumn → Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.contact.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * email field in *FooterColumn → Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.contact.primary.email
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email: prismic.RichTextField;

  /**
   * mobile field in *FooterColumn → Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.contact.primary.mobile
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mobile: prismic.RichTextField;

  /**
   * landline field in *FooterColumn → Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.contact.primary.landline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  landline: prismic.RichTextField;
}

/**
 * Contact variation for FooterColumn Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterColumnSliceContact = prismic.SharedSliceVariation<
  "contact",
  Simplify<FooterColumnSliceContactPrimary>,
  never
>;

/**
 * Primary content in *FooterColumn → Policy → Primary*
 */
export interface FooterColumnSlicePolicyPrimary {
  /**
   * Title field in *FooterColumn → Policy → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.policy.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * items field in *FooterColumn → Policy → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.policy.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<FooterColumnSlicePolicyPrimaryItemsItem>>;
}

/**
 * Policy variation for FooterColumn Slice
 *
 * - **API ID**: `policy`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterColumnSlicePolicy = prismic.SharedSliceVariation<
  "policy",
  Simplify<FooterColumnSlicePolicyPrimary>,
  never
>;

/**
 * Slice variation for *FooterColumn*
 */
type FooterColumnSliceVariation =
  | FooterColumnSliceDefault
  | FooterColumnSliceAddress
  | FooterColumnSliceContact
  | FooterColumnSlicePolicy;

/**
 * FooterColumn Shared Slice
 *
 * - **API ID**: `footer_column`
 * - **Description**: FooterColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterColumnSlice = prismic.SharedSlice<
  "footer_column",
  FooterColumnSliceVariation
>;

/**
 * Item in *FormInput → Default → Primary → items*
 */
export interface FormInputSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *FormInput → Default → Primary → items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: form_input.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *FormInput → Default → Primary*
 */
export interface FormInputSliceDefaultPrimary {
  /**
   * items field in *FormInput → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: form_input.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<FormInputSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for FormInput Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormInputSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormInputSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormInput*
 */
type FormInputSliceVariation = FormInputSliceDefault;

/**
 * FormInput Shared Slice
 *
 * - **API ID**: `form_input`
 * - **Description**: FormInput
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormInputSlice = prismic.SharedSlice<
  "form_input",
  FormInputSliceVariation
>;

/**
 * Primary content in *FramesImage → Default → Primary*
 */
export interface FramesImageSliceDefaultPrimary {
  /**
   * Image field in *FramesImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: frames_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for FramesImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FramesImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FramesImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FramesImage*
 */
type FramesImageSliceVariation = FramesImageSliceDefault;

/**
 * FramesImage Shared Slice
 *
 * - **API ID**: `frames_image`
 * - **Description**: FramesImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FramesImageSlice = prismic.SharedSlice<
  "frames_image",
  FramesImageSliceVariation
>;

/**
 * Item in *Grid3X3 → Default → Primary → Stack*
 */
export interface Grid3X3SliceDefaultPrimaryStackItem {
  /**
   * Number field in *Grid3X3 → Default → Primary → Stack*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid3_x3.default.primary.stack[].number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  number: prismic.TitleField;

  /**
   * Title field in *Grid3X3 → Default → Primary → Stack*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid3_x3.default.primary.stack[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Para field in *Grid3X3 → Default → Primary → Stack*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid3_x3.default.primary.stack[].para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;
}

/**
 * Primary content in *Grid3X3 → Default → Primary*
 */
export interface Grid3X3SliceDefaultPrimary {
  /**
   * Stack field in *Grid3X3 → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid3_x3.default.primary.stack[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stack: prismic.GroupField<Simplify<Grid3X3SliceDefaultPrimaryStackItem>>;
}

/**
 * Default variation for Grid3X3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Grid3X3SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Grid3X3SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Grid3X3*
 */
type Grid3X3SliceVariation = Grid3X3SliceDefault;

/**
 * Grid3X3 Shared Slice
 *
 * - **API ID**: `grid3_x3`
 * - **Description**: Grid3X3
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Grid3X3Slice = prismic.SharedSlice<
  "grid3_x3",
  Grid3X3SliceVariation
>;

/**
 * Primary content in *HeroSlider → Default → Primary*
 */
export interface HeroSliderSliceDefaultPrimary {
  /**
   * Title field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Para field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.default.primary.para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;

  /**
   * Image field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * BgImage field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.default.primary.bgimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgimage: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliderSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSlider → HeroSliderLeft → Primary*
 */
export interface HeroSliderSliceHeroSliderLeftPrimary {
  /**
   * Title field in *HeroSlider → HeroSliderLeft → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.heroSliderLeft.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Para field in *HeroSlider → HeroSliderLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.heroSliderLeft.primary.para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;

  /**
   * Image field in *HeroSlider → HeroSliderLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.heroSliderLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * BgImage field in *HeroSlider → HeroSliderLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.heroSliderLeft.primary.bgimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgimage: prismic.ImageField<never>;
}

/**
 * HeroSliderLeft variation for HeroSlider Slice
 *
 * - **API ID**: `heroSliderLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliderSliceHeroSliderLeft = prismic.SharedSliceVariation<
  "heroSliderLeft",
  Simplify<HeroSliderSliceHeroSliderLeftPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlider*
 */
type HeroSliderSliceVariation =
  | HeroSliderSliceDefault
  | HeroSliderSliceHeroSliderLeft;

/**
 * HeroSlider Shared Slice
 *
 * - **API ID**: `hero_slider`
 * - **Description**: HeroSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliderSlice = prismic.SharedSlice<
  "hero_slider",
  HeroSliderSliceVariation
>;

/**
 * Item in *LandingPage → Default → Primary → BgImage*
 */
export interface LandingPageSliceDefaultPrimaryBgimageItem {
  /**
   * BgImage field in *LandingPage → Default → Primary → BgImage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.default.primary.bgimage[].bgimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgimage: prismic.ImageField<never>;
}

/**
 * Item in *LandingPage → Default → Primary → items*
 */
export interface LandingPageSliceDefaultPrimaryItemsItem {
  /**
   * Numbers field in *LandingPage → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.default.primary.items[].numbers
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  numbers: prismic.RichTextField;

  /**
   * Description field in *LandingPage → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *LandingPage → Default → Primary*
 */
export interface LandingPageSliceDefaultPrimary {
  /**
   * Title field in *LandingPage → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Para field in *LandingPage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.default.primary.para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;

  /**
   * Image field in *LandingPage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * BgImage field in *LandingPage → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.default.primary.bgimage[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  bgimage: prismic.GroupField<
    Simplify<LandingPageSliceDefaultPrimaryBgimageItem>
  >;

  /**
   * items field in *LandingPage → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<LandingPageSliceDefaultPrimaryItemsItem>>;

  /**
   * NavLink field in *LandingPage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.default.primary.navlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navlink: prismic.LinkField;
}

/**
 * Default variation for LandingPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingPageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandingPageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LandingPage*
 */
type LandingPageSliceVariation = LandingPageSliceDefault;

/**
 * LandingPage Shared Slice
 *
 * - **API ID**: `landing_page`
 * - **Description**: LandingPage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingPageSlice = prismic.SharedSlice<
  "landing_page",
  LandingPageSliceVariation
>;

/**
 * Primary content in *MobileNavbr → Default → Primary*
 */
export interface MobileNavbrSliceDefaultPrimary {
  /**
   * NavLink field in *MobileNavbr → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_navbr.default.primary.navlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navlink: prismic.LinkField;

  /**
   * Name field in *MobileNavbr → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_navbr.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;
}

/**
 * Default variation for MobileNavbr Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MobileNavbrSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MobileNavbrSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MobileNavbr*
 */
type MobileNavbrSliceVariation = MobileNavbrSliceDefault;

/**
 * MobileNavbr Shared Slice
 *
 * - **API ID**: `mobile_navbr`
 * - **Description**: MobileNavbr
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MobileNavbrSlice = prismic.SharedSlice<
  "mobile_navbr",
  MobileNavbrSliceVariation
>;

/**
 * Primary content in *NavigationMenu → Default → Primary*
 */
export interface NavigationMenuSliceDefaultPrimary {
  /**
   * Name field in *NavigationMenu → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Link field in *NavigationMenu → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for NavigationMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationMenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigationMenu*
 */
type NavigationMenuSliceVariation = NavigationMenuSliceDefault;

/**
 * NavigationMenu Shared Slice
 *
 * - **API ID**: `navigation_menu`
 * - **Description**: NavigationMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationMenuSlice = prismic.SharedSlice<
  "navigation_menu",
  NavigationMenuSliceVariation
>;

/**
 * Primary content in *PageHeader → Default → Primary*
 */
export interface PageHeaderSliceDefaultPrimary {
  /**
   * Title field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageHeader*
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;

/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: PageHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSlice = prismic.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;

/**
 * Item in *PopularProducts → Default → Primary → Product*
 */
export interface PopularProductsSliceDefaultPrimaryProductItem {
  /**
   * Image field in *PopularProducts → Default → Primary → Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_products.default.primary.product[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Product_type field in *PopularProducts → Default → Primary → Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_products.default.primary.product[].product_type
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_type: prismic.RichTextField;

  /**
   * Product_name field in *PopularProducts → Default → Primary → Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_products.default.primary.product[].product_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_name: prismic.RichTextField;

  /**
   * Product_description field in *PopularProducts → Default → Primary → Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_products.default.primary.product[].product_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_description: prismic.RichTextField;

  /**
   * Price field in *PopularProducts → Default → Primary → Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_products.default.primary.product[].price
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price: prismic.RichTextField;
}

/**
 * Primary content in *PopularProducts → Default → Primary*
 */
export interface PopularProductsSliceDefaultPrimary {
  /**
   * Title field in *PopularProducts → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_products.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *PopularProducts → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_products.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Para field in *PopularProducts → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_products.default.primary.para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;

  /**
   * Product field in *PopularProducts → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_products.default.primary.product[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  product: prismic.GroupField<
    Simplify<PopularProductsSliceDefaultPrimaryProductItem>
  >;
}

/**
 * Default variation for PopularProducts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopularProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopularProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopularProducts*
 */
type PopularProductsSliceVariation = PopularProductsSliceDefault;

/**
 * PopularProducts Shared Slice
 *
 * - **API ID**: `popular_products`
 * - **Description**: PopularProducts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopularProductsSlice = prismic.SharedSlice<
  "popular_products",
  PopularProductsSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Steps → Default → Primary → Images*
 */
export interface StepsSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *Steps → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Steps → Default → Primary → Steps*
 */
export interface StepsSliceDefaultPrimaryStepsItem {
  /**
   * Heading field in *Steps → Default → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.steps[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Para field in *Steps → Default → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.steps[].para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;
}

/**
 * Primary content in *Steps → Default → Primary*
 */
export interface StepsSliceDefaultPrimary {
  /**
   * Title field in *Steps → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Images field in *Steps → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<StepsSliceDefaultPrimaryImagesItem>>;

  /**
   * Subtitle field in *Steps → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Steps field in *Steps → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  steps: prismic.GroupField<Simplify<StepsSliceDefaultPrimaryStepsItem>>;
}

/**
 * Default variation for Steps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Steps*
 */
type StepsSliceVariation = StepsSliceDefault;

/**
 * Steps Shared Slice
 *
 * - **API ID**: `steps`
 * - **Description**: Steps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSlice = prismic.SharedSlice<"steps", StepsSliceVariation>;

/**
 * Item in *Tetimonials → Default → Primary → Testimonials*
 */
export interface TetimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Para field in *Tetimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tetimonials.default.primary.testimonials[].para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;

  /**
   * Logo field in *Tetimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tetimonials.default.primary.testimonials[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Name field in *Tetimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tetimonials.default.primary.testimonials[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;
}

/**
 * Primary content in *Tetimonials → Default → Primary*
 */
export interface TetimonialsSliceDefaultPrimary {
  /**
   * Title field in *Tetimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tetimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Tetimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tetimonials.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Para field in *Tetimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tetimonials.default.primary.para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;

  /**
   * Testimonials field in *Tetimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tetimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<TetimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Tetimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TetimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TetimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Tetimonials*
 */
type TetimonialsSliceVariation = TetimonialsSliceDefault;

/**
 * Tetimonials Shared Slice
 *
 * - **API ID**: `tetimonials`
 * - **Description**: Tetimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TetimonialsSlice = prismic.SharedSlice<
  "tetimonials",
  TetimonialsSliceVariation
>;

/**
 * Item in *TextAndImageTabs → Default → Primary → items*
 */
export interface TextAndImageTabsSliceDefaultPrimaryItemsItem {
  /**
   * Numbers field in *TextAndImageTabs → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image_tabs.default.primary.items[].numbers
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  numbers: prismic.RichTextField;

  /**
   * Description field in *TextAndImageTabs → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image_tabs.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *TextAndImageTabs → Default → Primary*
 */
export interface TextAndImageTabsSliceDefaultPrimary {
  /**
   * Title field in *TextAndImageTabs → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image_tabs.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *TextAndImageTabs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image_tabs.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Para field in *TextAndImageTabs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image_tabs.default.primary.para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  para: prismic.RichTextField;

  /**
   * Image field in *TextAndImageTabs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image_tabs.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * BgImage field in *TextAndImageTabs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image_tabs.default.primary.bgimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgimage: prismic.ImageField<never>;

  /**
   * NavLink field in *TextAndImageTabs → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image_tabs.default.primary.navlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navlink: prismic.LinkField;

  /**
   * items field in *TextAndImageTabs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image_tabs.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<TextAndImageTabsSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for TextAndImageTabs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageTabsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextAndImageTabsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextAndImageTabs*
 */
type TextAndImageTabsSliceVariation = TextAndImageTabsSliceDefault;

/**
 * TextAndImageTabs Shared Slice
 *
 * - **API ID**: `text_and_image_tabs`
 * - **Description**: TextAndImageTabs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageTabsSlice = prismic.SharedSlice<
  "text_and_image_tabs",
  TextAndImageTabsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MainMenuDocument,
      MainMenuDocumentData,
      MainMenuDocumentDataSlicesSlice,
      MobileNavbarDocument,
      MobileNavbarDocumentData,
      MobileNavbarDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductsDocument,
      ProductsDocumentData,
      ProductsDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutUsHeaderSlice,
      AboutUsHeaderSliceDefaultPrimaryItemsItem,
      AboutUsHeaderSliceDefaultPrimaryStackItem,
      AboutUsHeaderSliceDefaultPrimary,
      AboutUsHeaderSliceVariation,
      AboutUsHeaderSliceDefault,
      BenefitsSlice,
      BenefitsSliceDefaultPrimaryCardItem,
      BenefitsSliceDefaultPrimary,
      BenefitsSliceVariation,
      BenefitsSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      FooterColumnSlice,
      FooterColumnSliceDefaultPrimaryItemsItem,
      FooterColumnSliceDefaultPrimary,
      FooterColumnSliceAddressPrimaryItemsItem,
      FooterColumnSliceAddressPrimary,
      FooterColumnSliceContactPrimary,
      FooterColumnSlicePolicyPrimaryItemsItem,
      FooterColumnSlicePolicyPrimary,
      FooterColumnSliceVariation,
      FooterColumnSliceDefault,
      FooterColumnSliceAddress,
      FooterColumnSliceContact,
      FooterColumnSlicePolicy,
      FormInputSlice,
      FormInputSliceDefaultPrimaryItemsItem,
      FormInputSliceDefaultPrimary,
      FormInputSliceVariation,
      FormInputSliceDefault,
      FramesImageSlice,
      FramesImageSliceDefaultPrimary,
      FramesImageSliceVariation,
      FramesImageSliceDefault,
      Grid3X3Slice,
      Grid3X3SliceDefaultPrimaryStackItem,
      Grid3X3SliceDefaultPrimary,
      Grid3X3SliceVariation,
      Grid3X3SliceDefault,
      HeroSliderSlice,
      HeroSliderSliceDefaultPrimary,
      HeroSliderSliceHeroSliderLeftPrimary,
      HeroSliderSliceVariation,
      HeroSliderSliceDefault,
      HeroSliderSliceHeroSliderLeft,
      LandingPageSlice,
      LandingPageSliceDefaultPrimaryBgimageItem,
      LandingPageSliceDefaultPrimaryItemsItem,
      LandingPageSliceDefaultPrimary,
      LandingPageSliceVariation,
      LandingPageSliceDefault,
      MobileNavbrSlice,
      MobileNavbrSliceDefaultPrimary,
      MobileNavbrSliceVariation,
      MobileNavbrSliceDefault,
      NavigationMenuSlice,
      NavigationMenuSliceDefaultPrimary,
      NavigationMenuSliceVariation,
      NavigationMenuSliceDefault,
      PageHeaderSlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceVariation,
      PageHeaderSliceDefault,
      PopularProductsSlice,
      PopularProductsSliceDefaultPrimaryProductItem,
      PopularProductsSliceDefaultPrimary,
      PopularProductsSliceVariation,
      PopularProductsSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      StepsSlice,
      StepsSliceDefaultPrimaryImagesItem,
      StepsSliceDefaultPrimaryStepsItem,
      StepsSliceDefaultPrimary,
      StepsSliceVariation,
      StepsSliceDefault,
      TetimonialsSlice,
      TetimonialsSliceDefaultPrimaryTestimonialsItem,
      TetimonialsSliceDefaultPrimary,
      TetimonialsSliceVariation,
      TetimonialsSliceDefault,
      TextAndImageTabsSlice,
      TextAndImageTabsSliceDefaultPrimaryItemsItem,
      TextAndImageTabsSliceDefaultPrimary,
      TextAndImageTabsSliceVariation,
      TextAndImageTabsSliceDefault,
    };
  }
}
