// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_header: dynamic(() => import("./AboutUsHeader")),
  benefits: dynamic(() => import("./Benefits")),
  faq: dynamic(() => import("./Faq")),
  footer_column: dynamic(() => import("./FooterColumn")),
  form_input: dynamic(() => import("./FormInput")),
  frames_image: dynamic(() => import("./FramesImage")),
  grid3_x3: dynamic(() => import("./Grid3X3")),
  hero_slider: dynamic(() => import("./HeroSlider")),
  landing_page: dynamic(() => import("./LandingPage")),
  mobile_navbr: dynamic(() => import("./MobileNavbr")),
  navigation_menu: dynamic(() => import("./NavigationMenu")),
  page_header: dynamic(() => import("./PageHeader")),
  popular_products: dynamic(() => import("./PopularProducts")),
  rich_text: dynamic(() => import("./RichText")),
  steps: dynamic(() => import("./Steps")),
  tetimonials: dynamic(() => import("./Tetimonials")),
  text_and_image_tabs: dynamic(() => import("./TextAndImageTabs")),
};
